import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const karla_font = Karla({
  subsets: ["latin"],
  variable: "--font-karla",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background antialiased dark font-karla",
        karla_font.variable
      )}>{children}</body>
    </html>
  );
}
